- hosts: localhost
  become: true
  pre_tasks:
    - name: Update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/i3config.yml
    - include: tasks/zshconfig.yml
    - include: tasks/vimconfig.yml
    - include: tasks/dropbox.yml
