#!/usr/bin/python3

import requests, sys, os, time, json, subprocess

def request_raw_schedule(stop, bus):
    r = requests.post("https://hellobuswsweb.tper.it/web-services/hello-bus.asmx/QueryHellobus", data={"fermata":stop, "linea":bus, "oraHHMM":""})
    raw_response = r.text
    response = raw_response.split('hellobus.asmx">')[1].split('<')[0]
    schedule = response.split("TperHellobus: ")[1]
    return schedule

def get_passed_time(threshold):
    last = 0
    if os.path.isfile("/tmp/tperlastcheck"):
        with open("/tmp/tperlastcheck", "r") as f:
            last = float(f.read())
    now = time.time()
    diff = now-last
    if diff > threshold:
        with open("/tmp/tperlastcheck", "w") as f:
            f.write(str(now))
        return True 
    else:
        return False

def get_next_schedule():
    stop = 604
    bus = 25
    cache_time = 60

    if get_passed_time(cache_time):
        info = request_raw_schedule(stop, bus)
        with open("/tmp/tperlasttime", "w") as f:
            f.write(info)
        return info
    else:
        with open("/tmp/tperlasttime", "r") as f:
            return f.read()

def get_keyboard_layout():
    raw = str(subprocess.check_output(["setxkbmap", "-query"]))
    layout = raw.split("layout:")[1].split("\\n")[0].strip()
    return layout
    

with os.popen("/usr/bin/i3status", mode='r', buffering=1) as status:
    while True:
        sys.stdout.flush()
        line = status.readline()
        if line == "":
            break
        if not line.startswith(","):
            print(line.strip())
            continue
        parsed = json.loads(line[1:])
        parsed.insert(0,{"name":"kblayout", "full_text":get_keyboard_layout()})
        parsed.insert(0,{"name":"bus", "full_text":get_next_schedule()})
        print(",%s" % (json.dumps(parsed)))
